2019-12-25 16:35:49,232 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 16:35:49,232 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 16:35:49,232 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 16:55:30,753 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 16:55:30,754 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 16:55:30,754 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 16:55:31,572 - test_login - INFO - 准备测试前置 - [test_login.py:22]
2019-12-25 16:55:31,575 - test_login - INFO - 开始测试：登录成功 - [test_login.py:27]
2019-12-25 16:55:32,055 - test_login - INFO - 结束测试：登录成功 - [test_login.py:37]
2019-12-25 16:55:32,056 - test_login - INFO - 开始测试：手机号码为空登录失败 - [test_login.py:27]
2019-12-25 16:55:32,151 - test_login - INFO - 结束测试：手机号码为空登录失败 - [test_login.py:37]
2019-12-25 16:55:32,152 - test_login - INFO - 开始测试：密码为空登录失败 - [test_login.py:27]
2019-12-25 16:55:32,231 - test_login - INFO - 结束测试：密码为空登录失败 - [test_login.py:37]
2019-12-25 16:55:32,231 - test_login - INFO - 开始测试：手机号码错误登录失败 - [test_login.py:27]
2019-12-25 16:55:32,445 - test_login - INFO - 结束测试：手机号码错误登录失败 - [test_login.py:37]
2019-12-25 16:55:32,446 - test_login - INFO - 开始测试：密码错误登录失败 - [test_login.py:27]
2019-12-25 16:55:32,643 - test_login - INFO - 结束测试：密码错误登录失败 - [test_login.py:37]
2019-12-25 16:55:32,643 - test_login - INFO - 测试后置处理 - [test_login.py:41]
2019-12-25 16:56:03,191 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 16:56:03,191 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 16:56:03,191 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 16:56:30,748 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 16:56:30,749 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 16:56:30,749 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 16:56:31,497 - test_login - INFO - 准备测试前置 - [test_login.py:22]
2019-12-25 16:56:31,501 - test_login - INFO - 开始测试：登录成功 - [test_login.py:27]
2019-12-25 16:56:31,770 - test_login - INFO - 结束测试：登录成功 - [test_login.py:37]
2019-12-25 16:56:31,770 - test_login - INFO - 开始测试：手机号码为空登录失败 - [test_login.py:27]
2019-12-25 16:56:31,850 - test_login - INFO - 结束测试：手机号码为空登录失败 - [test_login.py:37]
2019-12-25 16:56:31,850 - test_login - INFO - 开始测试：密码为空登录失败 - [test_login.py:27]
2019-12-25 16:56:31,927 - test_login - INFO - 结束测试：密码为空登录失败 - [test_login.py:37]
2019-12-25 16:56:31,927 - test_login - INFO - 开始测试：手机号码错误登录失败 - [test_login.py:27]
2019-12-25 16:56:32,142 - test_login - INFO - 结束测试：手机号码错误登录失败 - [test_login.py:37]
2019-12-25 16:56:32,142 - test_login - INFO - 开始测试：密码错误登录失败 - [test_login.py:27]
2019-12-25 16:56:32,335 - test_login - INFO - 结束测试：密码错误登录失败 - [test_login.py:37]
2019-12-25 16:56:32,336 - test_login - INFO - 测试后置处理 - [test_login.py:41]
2019-12-25 17:21:11,552 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 17:21:11,552 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 17:21:11,552 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 17:22:42,916 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 17:22:42,916 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 17:22:42,916 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 17:25:57,945 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 17:25:57,945 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 17:25:57,945 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 17:25:59,369 - API.API_8.testcases.test_login - INFO - 准备测试前置 - [test_login.py:22]
2019-12-25 17:25:59,370 - API.API_8.testcases.test_login - INFO - 开始测试：登录成功 - [test_login.py:27]
2019-12-25 17:25:59,624 - API.API_8.testcases.test_login - INFO - 结束测试：登录成功 - [test_login.py:37]
2019-12-25 17:25:59,624 - API.API_8.testcases.test_login - INFO - 开始测试：手机号码为空登录失败 - [test_login.py:27]
2019-12-25 17:25:59,698 - API.API_8.testcases.test_login - INFO - 结束测试：手机号码为空登录失败 - [test_login.py:37]
2019-12-25 17:25:59,699 - API.API_8.testcases.test_login - INFO - 开始测试：密码为空登录失败 - [test_login.py:27]
2019-12-25 17:25:59,774 - API.API_8.testcases.test_login - INFO - 结束测试：密码为空登录失败 - [test_login.py:37]
2019-12-25 17:25:59,774 - API.API_8.testcases.test_login - INFO - 开始测试：手机号码错误登录失败 - [test_login.py:27]
2019-12-25 17:25:59,976 - API.API_8.testcases.test_login - INFO - 结束测试：手机号码错误登录失败 - [test_login.py:37]
2019-12-25 17:25:59,976 - API.API_8.testcases.test_login - INFO - 开始测试：密码错误登录失败 - [test_login.py:27]
2019-12-25 17:26:00,172 - API.API_8.testcases.test_login - INFO - 结束测试：密码错误登录失败 - [test_login.py:37]
2019-12-25 17:26:00,172 - API.API_8.testcases.test_login - INFO - 测试后置处理 - [test_login.py:41]
2019-12-25 17:38:09,405 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 17:38:09,406 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 17:38:09,406 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 17:38:13,659 - test_login - INFO - 准备测试前置 - [test_login.py:22]
2019-12-25 17:38:13,659 - test_login - INFO - 开始测试：登录成功 - [test_login.py:27]
2019-12-25 17:38:13,905 - test_login - INFO - 结束测试：登录成功 - [test_login.py:37]
2019-12-25 17:38:13,905 - test_login - INFO - 开始测试：手机号码为空登录失败 - [test_login.py:27]
2019-12-25 17:38:13,986 - test_login - INFO - 结束测试：手机号码为空登录失败 - [test_login.py:37]
2019-12-25 17:38:13,986 - test_login - INFO - 开始测试：密码为空登录失败 - [test_login.py:27]
2019-12-25 17:38:14,064 - test_login - INFO - 结束测试：密码为空登录失败 - [test_login.py:37]
2019-12-25 17:38:14,064 - test_login - INFO - 开始测试：手机号码错误登录失败 - [test_login.py:27]
2019-12-25 17:38:14,264 - test_login - INFO - 结束测试：手机号码错误登录失败 - [test_login.py:37]
2019-12-25 17:38:14,265 - test_login - INFO - 开始测试：密码错误登录失败 - [test_login.py:27]
2019-12-25 17:38:14,482 - test_login - INFO - 结束测试：密码错误登录失败 - [test_login.py:37]
2019-12-25 17:38:14,483 - test_login - INFO - 测试后置处理 - [test_login.py:41]
2019-12-25 17:41:38,939 - case - INFO - 测试开始了 - [logger.py:30]
2019-12-25 17:41:38,939 - case - ERROR - 测试报错 - [logger.py:31]
2019-12-25 17:41:38,940 - case - INFO - 测试结束 - [logger.py:33]
2019-12-25 17:41:41,656 - test_login - INFO - 准备测试前置 - [test_login.py:22]
2019-12-25 17:41:41,656 - test_login - INFO - 开始测试：登录成功 - [test_login.py:27]
2019-12-25 17:41:41,894 - test_login - INFO - 结束测试：登录成功 - [test_login.py:37]
2019-12-25 17:41:41,894 - test_login - INFO - 开始测试：手机号码为空登录失败 - [test_login.py:27]
2019-12-25 17:41:41,972 - test_login - INFO - 结束测试：手机号码为空登录失败 - [test_login.py:37]
2019-12-25 17:41:41,972 - test_login - INFO - 开始测试：密码为空登录失败 - [test_login.py:27]
2019-12-25 17:41:42,052 - test_login - INFO - 结束测试：密码为空登录失败 - [test_login.py:37]
2019-12-25 17:41:42,053 - test_login - INFO - 开始测试：手机号码错误登录失败 - [test_login.py:27]
2019-12-25 17:41:42,250 - test_login - INFO - 结束测试：手机号码错误登录失败 - [test_login.py:37]
2019-12-25 17:41:42,251 - test_login - INFO - 开始测试：密码错误登录失败 - [test_login.py:27]
2019-12-25 17:41:42,448 - test_login - INFO - 结束测试：密码错误登录失败 - [test_login.py:37]
2019-12-25 17:41:42,448 - test_login - INFO - 测试后置处理 - [test_login.py:41]
